2021-04-24 05:22:53,785 INFO    MainThread:8310 [wandb_setup.py:_flush():69] setting env: {}
2021-04-24 05:22:53,786 INFO    MainThread:8310 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-24 05:22:53,786 INFO    MainThread:8310 [wandb_init.py:_log_setup():336] Logging user logs to /home/arora/kaggle/shopee/nbs/wandb/run-20210424_052253-3f0pv0v4/logs/debug.log
2021-04-24 05:22:53,786 INFO    MainThread:8310 [wandb_init.py:_log_setup():337] Logging internal logs to /home/arora/kaggle/shopee/nbs/wandb/run-20210424_052253-3f0pv0v4/logs/debug-internal.log
2021-04-24 05:22:53,787 INFO    MainThread:8310 [wandb_init.py:init():369] calling init triggers
2021-04-24 05:22:53,787 INFO    MainThread:8310 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-24 05:22:53,787 INFO    MainThread:8310 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 1vx08zf0
2021-04-24 05:22:53,789 INFO    MainThread:8310 [wandb_run.py:finish():1167] finishing run amanarora/shopee/1vx08zf0
2021-04-24 05:22:53,789 INFO    MainThread:8310 [jupyter.py:save_history():320] not saving jupyter history
2021-04-24 05:22:53,789 INFO    MainThread:8310 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-04-24 05:22:53,789 INFO    MainThread:8310 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-04-24 05:22:53,789 INFO    MainThread:8310 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-24 05:22:53,789 INFO    MainThread:8310 [wandb_run.py:_restore():1466] restore
2021-04-24 05:22:53,848 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 653
  total_bytes: 653
}

2021-04-24 05:22:54,914 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 653
  total_bytes: 5173
}

2021-04-24 05:22:55,017 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5173
  total_bytes: 5173
}

2021-04-24 05:22:55,120 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5173
  total_bytes: 5173
}

2021-04-24 05:22:55,222 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5173
  total_bytes: 5173
}

2021-04-24 05:22:55,324 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5173
  total_bytes: 5173
}

2021-04-24 05:22:55,426 INFO    MainThread:8310 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5173
  total_bytes: 5173
}

2021-04-24 05:22:56,521 INFO    MainThread:8310 [wandb_run.py:_show_files():1838] logging synced files
2021-04-24 05:22:56,525 INFO    MainThread:8310 [wandb_init.py:init():418] starting backend
2021-04-24 05:22:56,526 INFO    MainThread:8310 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-24 05:22:56,528 INFO    MainThread:8310 [backend.py:ensure_launched():123] starting backend process...
2021-04-24 05:22:56,564 INFO    MainThread:8310 [backend.py:ensure_launched():128] started backend process with pid: 9372
2021-04-24 05:22:56,566 INFO    MainThread:8310 [wandb_init.py:init():423] backend started and connected
2021-04-24 05:22:56,582 INFO    MainThread:8310 [wandb_init.py:init():465] updated telemetry
2021-04-24 05:22:56,583 INFO    MainThread:8310 [wandb_init.py:init():484] communicating current version
2021-04-24 05:22:57,240 INFO    MainThread:8310 [wandb_init.py:init():489] got version response 
2021-04-24 05:22:57,240 INFO    MainThread:8310 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-24 05:22:57,305 INFO    MainThread:8310 [wandb_init.py:init():522] starting run threads in backend
2021-04-24 05:22:57,328 INFO    MainThread:8310 [wandb_run.py:_console_start():1524] atexit reg
2021-04-24 05:22:57,329 INFO    MainThread:8310 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-04-24 05:22:57,329 INFO    MainThread:8310 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-04-24 05:22:57,329 INFO    MainThread:8310 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-24 05:22:57,329 INFO    MainThread:8310 [wandb_init.py:init():546] run started, returning control to user process
