2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_setup.py:_flush():69] setting env: {}
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_init.py:_log_setup():336] Logging user logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094822-1n8ur7v4/logs/debug.log
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_init.py:_log_setup():337] Logging internal logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094822-1n8ur7v4/logs/debug-internal.log
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_init.py:init():369] calling init triggers
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-24 09:48:22,358 INFO    MainThread:13753 [wandb_init.py:init():418] starting backend
2021-04-24 09:48:22,359 INFO    MainThread:13753 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-24 09:48:22,369 INFO    MainThread:13753 [backend.py:ensure_launched():123] starting backend process...
2021-04-24 09:48:22,376 INFO    MainThread:13753 [backend.py:ensure_launched():128] started backend process with pid: 13804
2021-04-24 09:48:22,377 INFO    MainThread:13753 [wandb_init.py:init():423] backend started and connected
2021-04-24 09:48:22,378 INFO    MainThread:13753 [wandb_init.py:init():465] updated telemetry
2021-04-24 09:48:22,379 INFO    MainThread:13753 [wandb_init.py:init():484] communicating current version
2021-04-24 09:48:22,926 INFO    MainThread:13753 [wandb_init.py:init():489] got version response 
2021-04-24 09:48:22,926 INFO    MainThread:13753 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-24 09:48:22,979 INFO    MainThread:13753 [wandb_init.py:init():522] starting run threads in backend
2021-04-24 09:48:23,022 INFO    MainThread:13753 [wandb_run.py:_console_start():1524] atexit reg
2021-04-24 09:48:23,022 INFO    MainThread:13753 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-24 09:48:23,023 INFO    MainThread:13753 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-24 09:48:23,026 INFO    MainThread:13753 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-24 09:48:23,026 INFO    MainThread:13753 [wandb_init.py:init():546] run started, returning control to user process
2021-04-24 09:48:28,609 INFO    MainThread:13753 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-24 09:48:28,609 INFO    MainThread:13753 [wandb_run.py:_restore():1466] restore
2021-04-24 09:48:30,662 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:48:30,777 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:48:30,984 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:48:31,086 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5007
  total_bytes: 5007
}

2021-04-24 09:48:31,188 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5007
  total_bytes: 5007
}

2021-04-24 09:48:31,289 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5007
  total_bytes: 5007
}

2021-04-24 09:48:31,391 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5007
  total_bytes: 5007
}

2021-04-24 09:48:31,493 INFO    MainThread:13753 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5007
  total_bytes: 5007
}

2021-04-24 09:48:32,621 INFO    MainThread:13753 [wandb_run.py:_show_files():1838] logging synced files
