2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_setup.py:_flush():69] setting env: {}
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_init.py:_log_setup():336] Logging user logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094933-1m4k0y3p/logs/debug.log
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_init.py:_log_setup():337] Logging internal logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094933-1m4k0y3p/logs/debug-internal.log
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_init.py:init():369] calling init triggers
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-24 09:49:33,466 INFO    MainThread:14896 [wandb_init.py:init():418] starting backend
2021-04-24 09:49:33,466 INFO    MainThread:14896 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-24 09:49:33,476 INFO    MainThread:14896 [backend.py:ensure_launched():123] starting backend process...
2021-04-24 09:49:33,483 INFO    MainThread:14896 [backend.py:ensure_launched():128] started backend process with pid: 14949
2021-04-24 09:49:33,484 INFO    MainThread:14896 [wandb_init.py:init():423] backend started and connected
2021-04-24 09:49:33,486 INFO    MainThread:14896 [wandb_init.py:init():465] updated telemetry
2021-04-24 09:49:33,486 INFO    MainThread:14896 [wandb_init.py:init():484] communicating current version
2021-04-24 09:49:34,031 INFO    MainThread:14896 [wandb_init.py:init():489] got version response 
2021-04-24 09:49:34,031 INFO    MainThread:14896 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-24 09:49:34,079 INFO    MainThread:14896 [wandb_init.py:init():522] starting run threads in backend
2021-04-24 09:49:34,180 INFO    MainThread:14896 [wandb_run.py:_console_start():1524] atexit reg
2021-04-24 09:49:34,180 INFO    MainThread:14896 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-24 09:49:34,180 INFO    MainThread:14896 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-24 09:49:34,182 INFO    MainThread:14896 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-24 09:49:34,182 INFO    MainThread:14896 [wandb_init.py:init():546] run started, returning control to user process
2021-04-24 09:50:14,406 INFO    MainThread:14896 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-24 09:50:14,408 INFO    MainThread:14896 [wandb_run.py:_restore():1466] restore
2021-04-24 09:50:16,462 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:50:17,094 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 838
}

2021-04-24 09:50:17,196 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4979
  total_bytes: 4979
}

2021-04-24 09:50:17,297 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4979
  total_bytes: 4979
}

2021-04-24 09:50:17,399 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4979
  total_bytes: 4979
}

2021-04-24 09:50:17,500 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4979
  total_bytes: 4979
}

2021-04-24 09:50:17,602 INFO    MainThread:14896 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4979
  total_bytes: 4979
}

2021-04-24 09:50:18,741 INFO    MainThread:14896 [wandb_run.py:_show_files():1838] logging synced files
